### ISSUE TITLE
Background build crashes if I visit another page soon after

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#1619]
Steps to reproduce locally:

1. clone https://github.com/nus-cs2103-AY2021S2/website
1. clone the submodule, as explained in the README
1. checkout the branch `cs2103`
1. run `markbind serve -o -b`
2. after the landing page is loaded, click on a few other links in the site-nav. 

The error:
>warn:  message=UNKNOWN: unknown error, open 'C:\repos\nus-cs2103\cs2103-website-base\_site\siteData.json', stack=Error: UNKNOWN: unknown error, open 'C:\repos\nus-cs2103\cs2103-website-base\_site\siteData.json', errno=-4094, code=UNKNOWN, syscall=open, path=C:\repos\nus-cs2103\cs2103-website-base\_site\siteData.json
error:  message=ENOENT: no such file or directory, open 'C:\repos\nus-cs2103\cs2103-website-base\_site\book\principles\separationOfConcernsPrinciple\unit-inElsewhere-asFlat._include_.html', stack=Error: ENOENT: no such file or directory, open 'C:\repos\nus-cs2103\cs2103-website-base\_site\book\principles\separationOfConcernsPrinciple\unit-inElsewhere-asFlat._include_.html'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at Object.<anonymous> (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\@markbind\core\src\Page\index.js:277:37)
    at initialize.exports.each (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\cheerio\lib\api\traversing.js:300:24)
    at Page.collectHeadingsAndKeywordsInContent (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\@markbind\core\src\Page\index.js:254:8)
    at Object.<anonymous> (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\@markbind\core\src\Page\index.js:292:16)
    at initialize.exports.each (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\cheerio\lib\api\traversing.js:300:24)
    at Page.collectHeadingsAndKeywordsInContent (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\@markbind\core\src\Page\index.js:254:8)
    at Object.<anonymous> (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\@markbind\core\src\Page\index.js:292:16)
    at initialize.exports.each (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\cheerio\lib\api\traversing.js:300:24)
    at Page.collectHeadingsAndKeywordsInContent (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\@markbind\core\src\Page\index.js:254:8)
    at Object.<anonymous> (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\@markbind\core\src\Page\index.js:292:16)
    at initialize.exports.each (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\cheerio\lib\api\traversing.js:300:24)
    at Page.collectHeadingsAndKeywordsInContent (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\@markbind\core\src\Page\index.js:254:8)
    at Object.<anonymous> (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\@markbind\core\src\Page\index.js:292:16)
    at initialize.exports.each (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\cheerio\lib\api\traversing.js:300:24), errno=-4058, syscall=open, code=ENOENT, path=C:\repos\nus-cs2103\cs2103-website-base\_site\book\principles\separationOfConcernsPrinciple\unit-inElsewhere-asFlat._include_.html
Unhandled rejection Error: Error while generating undefined
    at C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\@markbind\core\src\Site\index.js:1175:18
error:  message=ENOENT: no such file or directory, open 'C:\repos\nus-cs2103\cs2103-website-base\_site\book\oop\inheritance\what\unit-inElsewhere-asFlat._include_.html', stack=Error: ENOENT: no such file or directory, open 'C:\repos\nus-cs2103\cs2103-website-base\_site\book\oop\inheritance\what\unit-inElsewhere-asFlat._include_.html'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at Object.<anonymous> (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\@markbind\core\src\Page\index.js:277:37)
    at initialize.exports.each (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\cheerio\lib\api\traversing.js:300:24)
    at Page.collectHeadingsAndKeywordsInContent (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\@markbind\core\src\Page\index.js:254:8)
    at Object.<anonymous> (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\@markbind\core\src\Page\index.js:288:18)
    at initialize.exports.each (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\cheerio\lib\api\traversing.js:300:24)
    at Page.collectHeadingsAndKeywordsInContent (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\@markbind\core\src\Page\index.js:254:8)
    at Page.collectHeadingsAndKeywords (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\@markbind\core\src\Page\index.js:232:10)
    at Page.generate (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\@markbind\core\src\Page\index.js:489:10)
    at async C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\@markbind\core\src\Site\index.js:1167:11, errno=-4058, syscall=open, code=ENOENT, path=C:\repos\nus-cs2103\cs2103-website-base\_site\book\oop\inheritance\what\unit-inElsewhere-asFlat._include_.html
error:  message=ENOENT: no such file or directory, open 'C:\repos\nus-cs2103\cs2103-website-base\_site\book\oop\inheritance\what\unit-inElsewhere-asFlat._include_.html', stack=Error: ENOENT: no such file or directory, open 'C:\repos\nus-cs2103\cs2103-website-base\_site\book\oop\inheritance\what\unit-inElsewhere-asFlat._include_.html'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at Object.<anonymous> (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\@markbind\core\src\Page\index.js:277:37)
    at initialize.exports.each (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\cheerio\lib\api\traversing.js:300:24)
    at Page.collectHeadingsAndKeywordsInContent (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\@markbind\core\src\Page\index.js:254:8)
    at Object.<anonymous> (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\@markbind\core\src\Page\index.js:292:16)
    at initialize.exports.each (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\cheerio\lib\api\traversing.js:300:24)
    at Page.collectHeadingsAndKeywordsInContent (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\@markbind\core\src\Page\index.js:254:8)
    at Object.<anonymous> (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\@markbind\core\src\Page\index.js:292:16)
    at initialize.exports.each (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\cheerio\lib\api\traversing.js:300:24)
    at Page.collectHeadingsAndKeywordsInContent (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\@markbind\core\src\Page\index.js:254:8)
    at Object.<anonymous> (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\@markbind\core\src\Page\index.js:292:16)
    at initialize.exports.each (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\cheerio\lib\api\traversing.js:300:24)
    at Page.collectHeadingsAndKeywordsInContent (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\@markbind\core\src\Page\index.js:254:8)
    at Page.collectHeadingsAndKeywords (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\@markbind\core\src\Page\index.js:232:10)
    at Page.generate (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\@markbind\core\src\Page\index.js:489:10), errno=-4058, syscall=open, code=ENOENT, path=C:\repos\nus-cs2103\cs2103-website-base\_site\book\oop\inheritance\what\unit-inElsewhere-asFlat._include_.html
error:  message=ENOENT: no such file or directory, open 'C:\repos\nus-cs2103\cs2103-website-base\_site\book\oop\objects\encapsulation\unit-inElsewhere-asFlat._include_.html', stack=Error: ENOENT: no such file or directory, open 'C:\repos\nus-cs2103\cs2103-website-base\_site\book\oop\objects\encapsulation\unit-inElsewhere-asFlat._include_.html'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at Object.<anonymous> (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\@markbind\core\src\Page\index.js:277:37)
    at initialize.exports.each (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\cheerio\lib\api\traversing.js:300:24)
    at Page.collectHeadingsAndKeywordsInContent (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\@markbind\core\src\Page\index.js:254:8)
    at Object.<anonymous> (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\@markbind\core\src\Page\index.js:292:16)
    at initialize.exports.each (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\cheerio\lib\api\traversing.js:300:24)
    at Page.collectHeadingsAndKeywordsInContent (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\@markbind\core\src\Page\index.js:254:8)
    at Object.<anonymous> (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\@markbind\core\src\Page\index.js:292:16)
    at initialize.exports.each (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\cheerio\lib\api\traversing.js:300:24)
    at Page.collectHeadingsAndKeywordsInContent (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\@markbind\core\src\Page\index.js:254:8)
    at Object.<anonymous> (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\@markbind\core\src\Page\index.js:292:16)
    at initialize.exports.each (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\cheerio\lib\api\traversing.js:300:24)
    at Page.collectHeadingsAndKeywordsInContent (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\@markbind\core\src\Page\index.js:254:8)
    at Object.<anonymous> (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\@markbind\core\src\Page\index.js:292:16)
    at initialize.exports.each (C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\cheerio\lib\api\traversing.js:300:24), errno=-4058, syscall=open, code=ENOENT, path=C:\repos\nus-cs2103\cs2103-website-base\_site\book\oop\objects\encapsulation\unit-inElsewhere-asFlat._include_.html

Let me know if you are unable to reproduce...

**Comment by wxwxwxwx9** [comment]
Hmm, I wasn't able to replicate this (the crash). Seems to be working fine for me. Perhaps others can try replicating this.

**Comment by ryoarmanda** [comment]
Couldn't reproduce this as well, but so far I have only tried it in one run. My current guess that this is probably an intermittent issue caused by the asynchronous nature of the page generation.

We can still investigate this further by trying multiple runs or reading from the provided stack trace. @damithc have you experienced this error/crash quite consistently (i.e. more than once) or is it just a one-off so far?

**Comment by damithc** [comment]
Turns out it has nothing to do with clicking. The the command fails on its own after a while with the given error. And it seems to happen almost every time (happened 5/5 most recent tries).

**Comment by ryoarmanda** [comment]
I tried to run the background build without interruption and it still cleanly finishes... it's a tricky problem here, I would need to make do with just the error trace (I don't want to readily say there's nothing we can do for this).

Here is my investigation on this:

> From the trace, there's a `warn` log about an `unknown` error in opening the siteData file, then there's a bunch of `no such file` error following it, each corresponding to an asynchronous page generation callback, and an `unhandled rejection` error. The crash might be able to be explained by the `unhandled rejection` error (since iirc node would crash if encounters that).
> 
> I see that FS operation regarding siteData is only done in one method so the `warn` error is probably from there, and interestingly, if the method ever happen to encounter error in writing the siteData, it will call a utility function to print out a `warn` log of the error, and then removes the entire output folder's contents. Knowing our circumstances, this can explain the reason of all the rejections. All of the callbacks can't find some generated files because all of the files are already gone.
>
> I'm not sure yet of the reason of the FS error, but I think it's probably because of IO race conditions / overwhelming requests to access it, since in background build, we write the siteData after each page build to ensure search data is up to date (which in retrospect, we can do better about it).

TL;DR - The crash is likely because of the unhandled rejections. The catalyst of the rejections is probably overwhelming requests to write siteData after each page build, which causes FS error and an utility function call then deletes the whole output folder's contents, hence why page generation callbacks throws file not found errors and rejects.

This is just my speculation, but it's a good start. I have a trial PR to test whether this is the case. In it, I just disabled the "write to siteData" call after each page build, handle rejections when it happens, and fix an error message so that it outputs the correct. I also added an extra `warn` log to give a heads up whether the utility function is called.

As unfortunately you are the only one we know that can reproduce the errors reliably, I might need to ask your help in testing this (not ideal I know... :/). If you have the time, can you please check out the trial PR and try to do the background build from there, see if the error persists?

If you have the MarkBind repo cloned, you can checkout the trial PR by:
```
git fetch origin pull/1621/head:1621-trial
git checkout 1621-trial
```
(if not possible, can try changing `origin` to `upstream`)

**Comment by damithc** [comment]
Thanks for the follow up work @ryoarmanda 
Will give it a try and let you know how it goes.

**Comment by damithc** [comment]
@ryoarmanda here's the error message I got from this version. 
* BTW, the precise version of the CS2103 website I'm using is https://github.com/nus-cs2103/website-base
* I linked my MarkBind to the version in this PR for this experiment but how to confirm (as there is no change in behavior)?. Perhaps you can put some extra log messages in this version to confirm that I'm using the correct version by looking at the log output?

>v3.0.4
info: Website generation (lazy) started at 2:06:58 am
info: Building assets...
info: Assets built
info: Generating landing page...
info: Landing page built, other pages will be built as you navigate to them!
info: Site data built
info: Website generation (lazy) complete! Total build time: 18.529s
info: Serving "C:\repos\nus-cs2103\cs2103-website-base\_site" at http://127.0.0.1:8080
info: Press CTRL+C to stop ...
info: Building files that are not viewed in the background...
Deprecated as of 10.7.0. highlight(lang, code, ...args) has been deprecated.
Deprecated as of 10.7.0. Please use highlight(code, options) instead.
https://github.com/highlightjs/highlight.js/issues/2277
warn:  message=UNKNOWN: unknown error, open 'C:\repos\nus-cs2103\cs2103-website-base\_site\siteData.json', stack=Error: UNKNOWN: unknown error, open 'C:\repos\nus-cs2103\cs2103-website-base\_site\siteData.json', errno=-4094, code=UNKNOWN, syscall=open, path=C:\repos\nus-cs2103\cs2103-website-base\_site\siteData.json
error: Failed to copy asset markbind-plugin-anchors.css for plugin markbind-plugin-anchors
Error: ENOENT: no such file or directory, mkdir 'C:\repos\nus-cs2103\cs2103-website-base\_site\plugins\markbind-plugin-anchors'
ERROR: Error: EPERM: operation not permitted, watch 'C:\repos\nus-cs2103\cs2103-website-base\_site\book\designFundamentals\coupling\how'
    at FSWatcher.<computed> (internal/fs/watchers.js:218:26)
    at Object.watch (fs.js:1582:34)
    at createFsWatchInstance (C:\repos\markbind\markbind\packages\cli\node_modules\chokidar\lib\nodefs-handler.js:119:15)
    at setFsWatchListener (C:\repos\markbind\markbind\packages\cli\node_modules\chokidar\lib\nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (C:\repos\markbind\markbind\packages\cli\node_modules\chokidar\lib\nodefs-handler.js:331:14)
    at NodeFsHandler._handleDir (C:\repos\markbind\markbind\packages\cli\node_modules\chokidar\lib\nodefs-handler.js:559:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async NodeFsHandler._addToNodeFs (C:\repos\markbind\markbind\packages\cli\node_modules\chokidar\lib\nodefs-handler.js:609:16) {
  errno: -4048,
  syscall: 'watch',
  code: 'EPERM',
  path: 'C:\\repos\\nus-cs2103\\cs2103-website-base\\_site\\book\\designFundamentals\\coupling\\how',
  filename: 'C:\\repos\\nus-cs2103\\cs2103-website-base\\_site\\book\\designFundamentals\\coupling\\how'
}
error:  message=ENOENT: no such file or directory, open 'C:\repos\nus-cs2103\cs2103-website-base\_site\book\cppToJava\misc\constants\index.html', stack=Error: ENOENT: no such file or directory, open 'C:\repos\nus-cs2103\cs2103-website-base\_site\book\cppToJava\misc\constants\index.html', errno=-4058, code=ENOENT, syscall=open, path=C:\repos\nus-cs2103\cs2103-website-base\_site\book\cppToJava\misc\constants\index.html
Unhandled rejection Error: Error while generating undefined
    at C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Site\index.js:1175:18
error:  message=ENOENT: no such file or directory, open 'C:\repos\nus-cs2103\cs2103-website-base\_site\book\cppToJava\inheritance\basic\index.html', stack=Error: ENOENT: no such file or directory, open 'C:\repos\nus-cs2103\cs2103-website-base\_site\book\cppToJava\inheritance\basic\index.html', errno=-4058, code=ENOENT, syscall=open, path=C:\repos\nus-cs2103\cs2103-website-base\_site\book\cppToJava\inheritance\basic\index.html
error:  message=ENOENT: no such file or directory, open 'C:\repos\nus-cs2103\cs2103-website-base\_site\book\cppToJava\inheritance\index.html', stack=Error: ENOENT: no such file or directory, open 'C:\repos\nus-cs2103\cs2103-website-base\_site\book\cppToJava\inheritance\index.html', errno=-4058, code=ENOENT, syscall=open, path=C:\repos\nus-cs2103\cs2103-website-base\_site\book\cppToJava\inheritance\index.html
error:  message=ENOENT: no such file or directory, open 'C:\repos\nus-cs2103\cs2103-website-base\_site\book\uml\objectDiagrams\introduction\unit-inElsewhere-asFlat._include_.html', stack=Error: ENOENT: no such file or directory, open 'C:\repos\nus-cs2103\cs2103-website-base\_site\book\uml\objectDiagrams\introduction\unit-inElsewhere-asFlat._include_.html'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at Object.<anonymous> (C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Page\index.js:277:37)
    at initialize.exports.each (C:\repos\markbind\markbind\packages\cli\node_modules\cheerio\lib\api\traversing.js:300:24)
    at Page.collectHeadingsAndKeywordsInContent (C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Page\index.js:254:8)
    at Object.<anonymous> (C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Page\index.js:288:18)
    at initialize.exports.each (C:\repos\markbind\markbind\packages\cli\node_modules\cheerio\lib\api\traversing.js:300:24)
    at Page.collectHeadingsAndKeywordsInContent (C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Page\index.js:254:8)
    at Object.<anonymous> (C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Page\index.js:292:16)
    at initialize.exports.each (C:\repos\markbind\markbind\packages\cli\node_modules\cheerio\lib\api\traversing.js:300:24)
    at Page.collectHeadingsAndKeywordsInContent (C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Page\index.js:254:8)
    at Object.<anonymous> (C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Page\index.js:292:16)
    at initialize.exports.each (C:\repos\markbind\markbind\packages\cli\node_modules\cheerio\lib\api\traversing.js:300:24)
    at Page.collectHeadingsAndKeywordsInContent (C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Page\index.js:254:8)
    at Page.collectHeadingsAndKeywords (C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Page\index.js:232:10)
    at Page.generate (C:\repos\markbind\markbind\packages\cli\node_modules\@markbind\core\src\Page\index.js:489:10), errno=-4058, syscall=open, code=ENOENT, path=C:\repos\nus-cs2103\cs2103-website-base\_site\book\uml\objectDiagrams\introduction\unit-inElsewhere-asFlat._include_.html

**Comment by ryoarmanda** [comment]
> BTW, the precise version of the CS2103 website I'm using is https://github.com/nus-cs2103/website-base

Just to confirm, are you working on the `master` branch or other branches?

> I linked my MarkBind to the version in this PR for this experiment but how to confirm (as there is no change in behavior)?. Perhaps you can put some extra log messages in this version to confirm that I'm using the correct version by looking at the log output?

Thanks for the suggestion, I added some changes to the PR, now we can identify whether the trial is used by looking at the logged version (should be `v3.0.4-trial`).

Regarding the error log you provided, not sure if it's properly linked. The unhandled rejection error still says `Error while generating undefined`, pretty sure I already fixed it in the trial PR. If there's an error during page generation, the log would have something like this now (I forced to do rejection for this one):

```
error: Asynchronous generation failed
error:  message=Error while generating C:\Users\Ryo Armanda\projects\website-base\admin\appendixA-principles.md, stack=Error: Error while generating C:\Users\Ryo Armanda\projects\website-base\admin\appendixA-principles.md
    ...
```

**Comment by damithc** [comment]
> Just to confirm, are you working on the `master` branch or other branches?

I'm using `cs2103` branch. On Windows 10.

Yes, It's possible that the new version wasn't linked properly before. There was an error from the `npm link` command this time that I probably didn't spot last time. So, I used `npm link --force` to overcome that error this time.

After linking properly (I hope), I'm getting this error for `markbind serve -o`. 
>error: Oops! It seems that you didn't have the default file index.md|mbd.

The error goes away after I unlink and go back to the production version.

**Comment by damithc** [comment]
BTW, i'm using this method to link https://markbind.org/devdocs/devGuide/settingUp.html#setting-up-the-dev-environment
I hope it's the correct method.

The error I get for `npm link` (when run inside `packages/cli` folder) is the following:
>$ npm link
npm notice created a lockfile as package-lock.json. You should commit this file.
added 3 packages from 8 contributors and audited 854 packages in 7.24s
>
>28 packages are looking for funding
  run `npm fund` for details
>
>found 4 vulnerabilities (1 moderate, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details
npm ERR! code EEXIST
npm ERR! path C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\index.js
npm ERR! dest C:\Users\dcsdcr\AppData\Roaming\npm\markbind.cmd
npm ERR! EEXIST: file already exists, cmd shim 'C:\Users\dcsdcr\AppData\Roaming\npm\node_modules\markbind-cli\index.js' -> 'C:\Users\dcsdcr\AppData\Roaming\npm\markbind.cmd'
npm ERR! File exists: C:\Users\dcsdcr\AppData\Roaming\npm\markbind.cmd
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.
>
>npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dcsdcr\AppData\Roaming\npm-cache\_logs\2021-07-08T06_30_49_061Z-debug.log

`npm link --force` gets rid of the above error but I wonder it that is related to the following error that I got for the subsequent `markbind -o` command.

>error: Oops! It seems that you didn't have the default file index.md|mbd.

**Comment by ryoarmanda** [comment]
Can you try running `npm run setup` (the third step in the guide)? I usually just use that when checking out development code. If I'm not wrong, it also does the linking for you.

**Comment by ong6** [comment]
> Turns out it has nothing to do with clicking. The the command fails on its own (without any clicking) after a while with the given error. And it seems to happen almost every time (happened 5/5 most recent tries).

Hi, I have tried to replicate this issue but I cannot seem to reproduce or get any errors? Seems to be working fine on my end.

**Comment by damithc** [comment]
> Hi, I have tried to replicate this issue but I cannot seem to reproduce or get any errors? Seems to be working fine on my end.

Thanks for checking @ong6 
Did you try with the cs2103 website? It may have to do with the site itself.
Or it could be specific to my computer.

**Comment by ong6** [comment]
@damithc Yep, I tried it and there were no errors for me. Perhaps the error is specific to your computer?

**Comment by damithc** [comment]
Seems like something specific to my local setup. This is when working on https://github.com/se-edu/guides
Failed the same way 3/3 times, but different errors:

![image](https://user-images.githubusercontent.com/1673303/131643984-5f872da1-9bfa-4c00-aea7-9d71d8674b4a.png)
![image](https://user-images.githubusercontent.com/1673303/131644295-2a7b68a9-1007-4acd-8232-85d1167a2bf2.png)

**Comment by ong6** [comment]
Thanks for the screenshots @damithc I will look into this and see if I can replicate/ solve this issue

**Comment by ryoarmanda** [comment]
Thanks for lending a hand @ong6 ! A while back I have written one possible cause on the trial PR (see #1632) but we're still unsure on whether that is what's happening on prof's side because we could not reproduce it. Feel free to investigate further :)
