### ISSUE TITLE
`init` and `serve` commands are throwing errors

### ISSUE THREAD

**Issue by riyadh-h** [MarkBind/markbind#1656]
**Tell us about your environment**
I am using a Windows 10 machine and executing MarkBind's commands through the WSL terminal integrated into VSCode.

* **MarkBind Version:** v3.0.6

**What did you do? Please include the actual source code causing the issue.**
I tried creating a new MarkBind instance using the command `markbind init`.

I believe this statement from `packages/cli/index.js` (Lines 44-46) is what's causing this issue:

```js
program
  .addHelpText('beforeAll', printHeader())
  .showHelpAfterError('(run "markbind --help" to list commands)');
```

**What did you expect to happen?**
A new MarkBind instance would be created.

**What actually happened? Please include the actual, raw output.**
Error messages are shown on the terminal as follows:
```
  __  __                  _      ____    _               _ 
 |  \/  |   __ _   _ __  | | __ | __ )  (_)  _ __     __| |
 | |\/| |  / _` | | '__| | |/ / |  _ \  | | | '_ \   / _` |
 | |  | | | (_| | | |    |   <  | |_) | | | | | | | | (_| |
 |_|  |_|  \__,_| |_|    |_|\_\ |____/  |_| |_| |_|  \__,_|

 v3.0.6
error: uncaughtException: program.addHelpText is not a function date=Sun Aug 22 2021 09:35:13 GMT+0800 (Singapore Standard Time), pid=171, uid=1000, gid=1000, cwd=/mnt/c/Users/riyadh/Dropbox/NUS/CP3108BIWM/markbind, execPath=/usr/local/bin/node, version=v14.17.4, argv=[/usr/local/bin/node, /usr/local/bin/markbind, init, ./sandbox], rss=81453056, heapTotal=66207744, heapUsed=35858440, external=3420783, arrayBuffers=42922, loadavg=[0.52, 0.58, 0.59], uptime=8449.84
TypeError: program.addHelpText is not a function
    at Object.<anonymous> (/mnt/c/Users/riyadh/Dropbox/NUS/CP3108BIWM/markbind/packages/cli/index.js:45:4)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
error: uncaughtException: program.addHelpText is not a function date=Sun Aug 22 2021 09:35:13 GMT+0800 (Singapore Standard Time), pid=171, uid=1000, gid=1000, cwd=/mnt/c/Users/riyadh/Dropbox/NUS/CP3108BIWM/markbind, execPath=/usr/local/bin/node, version=v14.17.4, argv=[/usr/local/bin/node, /usr/local/bin/markbind, init, ./sandbox], rss=81530880, heapTotal=66207744, heapUsed=35958336, external=1591872, arrayBuffers=42946, loadavg=[0.52, 0.58, 0.59], uptime=8449.84
TypeError: program.addHelpText is not a function
    at Object.<anonymous> (/mnt/c/Users/riyadh/Dropbox/NUS/CP3108BIWM/markbind/packages/cli/index.js:45:4)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by tlylt** [comment]
Hi @riyadh-h , there is a dependency update that require you to change to a newer version of commander.js.
Could you run `npm run setup` in the root directory again to get all dependencies up to date?

**Comment by riyadh-h** [comment]
Hello @tlylt!

Ah, I see
I tried running `npm run setup`, but I got some permission issues from the system.
I'll try to get them fixed first 👍.

**Comment by riyadh-h** [comment]
> Hello @tlylt!
> 
> Ah, I see
> I tried running `npm run setup`, but I got some permission issues from the system.
> I'll try to get them fixed first 👍.

Works perfectly now. Thank you for the help, @tlylt!
