### ISSUE TITLE
Live reload: long loop of rebuilding 0 pages

### ISSUE THREAD

**Issue by damithc** [MarkBind/markbind#181]
![image](https://user-images.githubusercontent.com/1673303/38096577-cdfff6b4-33a5-11e8-90d7-c4160614dffb.png)
![image](https://user-images.githubusercontent.com/1673303/38096619-f1ea3cec-33a5-11e8-9945-6712ea4bb477.png)

On rare occassions, live reload goes into a long sequence of rebuilds.  Eventually crashed with this error.
```
info: Reload for file change: C:\repos\nus-te3201\website\common\search.md
info: Rebuilding 1 pages
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\repos\nus-te3201\website\_site\book-adapted\index.html'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at SendStream.file (C:\Users\damithch\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\live-server\index.js:60:23)
    at emitTwo (events.js:126:13)
    at SendStream.emit (events.js:214:7)
    at onstat (C:\Users\damithch\AppData\Roaming\npm\node_modules\markbind-cli\node_modules\send\index.js:729:10)
    at FSReqWrap.oncomplete (fs.js:153:5)
```

Not sure what action caused it. Just recording here for future reference.

**Comment by damithc** [comment]
Happened again. This time the error given was different but started with a long list of rebuilds and ended with having to restart the server.

**Comment by rachx** [comment]
Is the long list of rebuilds always of 0 pages?

Was there an error before the long list of rebuild started?

Usually I won't expect to see consecutive rebuilding (without a info: page rebuilt) between.

**Comment by damithc** [comment]
I don't think there was an error before. Output looks normal before the error in the first screenshot.
It was a long series of `0 pages`, but I remember seeing a solitary `2 pages` in the middle of at least a hundred of `0 pages`. Next time I'll post the full log. Note that this long list comes in at once (e.g., in less than 1 second)

**Comment by damithc** [comment]
Here's a more complete log:
```
info: Reload for file change: C:\repos\nus-te3201\website\book\designApproaches\topDownBottomUp\what\exercises.md
info: Reload for file change: C:\repos\nus-te3201\website\book\designApproaches\topDownBottomUp\what\q-tick-trueFalse.md
info: Reload for file change: C:\repos\nus-te3201\website\book\designApproaches\agileDesign\what\full.md
info: Reload for file change: C:\repos\nus-te3201\website\book\designApproaches\agileDesign\what\exercises.md
info: Reload for file change: C:\repos\nus-te3201\website\book\designApproaches\agileDesign\what\q-tick-trueFalse.md
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Rebuilding 0 pages
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
info: Pages rebuilt
```
BTW, some of the files are not touched at all, not involved at all with the files edited or even open in the IDE.

**Comment by damithc** [comment]
Haven't seen this for a while. Will reopen if it does reappear.
