### ISSUE TITLE
Node v18.8.0 is incompatible

### ISSUE THREAD

**Issue by petermonky** [MarkBind/markbind#2039]
### Please confirm that you have searched existing issues in the repo

Yes, I have searched the existing issues

### Tell us about your environment

macOS Ventura 13.0

### MarkBind version

4.0.2

### What did you do? Describe the bug

MarkBind seems to be incompatible with later versions of Node (notably v18.8.0). I am not too sure whether this issue is specific to my device; if it's universal, I think there may be a need to update the documentation or bump MarkBind to be compatible with later versions of Node.

### Steps to reproduce

Run `markbind serve -d` with Node v.18.8.0.

### Expected behavior

The application is served correctly; e.g. with Node v.14.17.2:

```
peter@Peters-MacBook-Pro mbtest % node --version
v14.17.2
peter@Peters-MacBook-Pro mbtest % markbind serve -d
  __  __                  _      ____    _               _ 
 |  \/  |   __ _   _ __  | | __ | __ )  (_)  _ __     __| |
 | |\/| |  / _` | | '__| | |/ / |  _ \  | | | '_ \   / _` |
 | |  | | | (_| | | |    |   <  | |_) | | | | | | | | (_| |
 |_|  |_|  \__,_| |_|    |_|\_\ |____/  |_| |_| |_|  \__,_|
                                                           
 v4.0.2
info: Changes detected in MarkBind Vue Source Files: 
Bundle is regenerated by webpack and built pages are re-rendered with the latest bundle.
info: Website generation started at 19:59:44
info: Building assets...
info: Assets built
info: Generating pages...
[======] 6 / 6 pages built
info: Pages built
webpack built 2ca50551eda74b2c3441 in 935ms
ℹ ｢wdm｣: Hash: 2ca50551eda74b2c3441
Version: webpack 4.46.0
Time: 935ms
Built at: 17/11/2022 19:59:45
                                Asset      Size    Chunks             Chunk Names
          fonts/KaTeX_AMS-Regular.ttf  62.1 KiB            [emitted]  
         fonts/KaTeX_AMS-Regular.woff  32.7 KiB            [emitted]  
        fonts/KaTeX_AMS-Regular.woff2  27.4 KiB            [emitted]  
     fonts/KaTeX_Caligraphic-Bold.ttf  12.1 KiB            [emitted]  
    fonts/KaTeX_Caligraphic-Bold.woff  7.54 KiB            [emitted]  
   fonts/KaTeX_Caligraphic-Bold.woff2  6.75 KiB            [emitted]  
  fonts/KaTeX_Caligraphic-Regular.ttf  12.1 KiB            [emitted]  
 fonts/KaTeX_Caligraphic-Regular.woff  7.48 KiB            [emitted]  
fonts/KaTeX_Caligraphic-Regular.woff2  6.75 KiB            [emitted]  
         fonts/KaTeX_Fraktur-Bold.ttf  19.1 KiB            [emitted]  
        fonts/KaTeX_Fraktur-Bold.woff    13 KiB            [emitted]  
       fonts/KaTeX_Fraktur-Bold.woff2  11.1 KiB            [emitted]  
      fonts/KaTeX_Fraktur-Regular.ttf  19.1 KiB            [emitted]  
     fonts/KaTeX_Fraktur-Regular.woff  12.9 KiB            [emitted]  
    fonts/KaTeX_Fraktur-Regular.woff2  11.1 KiB            [emitted]  
            fonts/KaTeX_Main-Bold.ttf  50.1 KiB            [emitted]  
           fonts/KaTeX_Main-Bold.woff  29.2 KiB            [emitted]  
          fonts/KaTeX_Main-Bold.woff2  24.7 KiB            [emitted]  
      fonts/KaTeX_Main-BoldItalic.ttf  32.2 KiB            [emitted]  
     fonts/KaTeX_Main-BoldItalic.woff    19 KiB            [emitted]  
    fonts/KaTeX_Main-BoldItalic.woff2  16.4 KiB            [emitted]  
          fonts/KaTeX_Main-Italic.ttf  32.8 KiB            [emitted]  
         fonts/KaTeX_Main-Italic.woff  19.2 KiB            [emitted]  
        fonts/KaTeX_Main-Italic.woff2  16.6 KiB            [emitted]  
         fonts/KaTeX_Main-Regular.ttf  52.3 KiB            [emitted]  
        fonts/KaTeX_Main-Regular.woff  30.1 KiB            [emitted]  
       fonts/KaTeX_Main-Regular.woff2  25.7 KiB            [emitted]  
      fonts/KaTeX_Math-BoldItalic.ttf  30.5 KiB            [emitted]  
     fonts/KaTeX_Math-BoldItalic.woff  18.2 KiB            [emitted]  
    fonts/KaTeX_Math-BoldItalic.woff2    16 KiB            [emitted]  
          fonts/KaTeX_Math-Italic.ttf  30.6 KiB            [emitted]  
         fonts/KaTeX_Math-Italic.woff  18.3 KiB            [emitted]  
        fonts/KaTeX_Math-Italic.woff2  16.1 KiB            [emitted]  
       fonts/KaTeX_SansSerif-Bold.ttf  23.9 KiB            [emitted]  
      fonts/KaTeX_SansSerif-Bold.woff  14.1 KiB            [emitted]  
     fonts/KaTeX_SansSerif-Bold.woff2  11.9 KiB            [emitted]  
     fonts/KaTeX_SansSerif-Italic.ttf  21.8 KiB            [emitted]  
    fonts/KaTeX_SansSerif-Italic.woff  13.8 KiB            [emitted]  
   fonts/KaTeX_SansSerif-Italic.woff2  11.7 KiB            [emitted]  
    fonts/KaTeX_SansSerif-Regular.ttf    19 KiB            [emitted]  
   fonts/KaTeX_SansSerif-Regular.woff    12 KiB            [emitted]  
  fonts/KaTeX_SansSerif-Regular.woff2  10.1 KiB            [emitted]  
       fonts/KaTeX_Script-Regular.ttf  16.3 KiB            [emitted]  
      fonts/KaTeX_Script-Regular.woff  10.3 KiB            [emitted]  
     fonts/KaTeX_Script-Regular.woff2  9.42 KiB            [emitted]  
        fonts/KaTeX_Size1-Regular.ttf  11.9 KiB            [emitted]  
       fonts/KaTeX_Size1-Regular.woff  6.34 KiB            [emitted]  
      fonts/KaTeX_Size1-Regular.woff2  5.34 KiB            [emitted]  
        fonts/KaTeX_Size2-Regular.ttf  11.2 KiB            [emitted]  
       fonts/KaTeX_Size2-Regular.woff  6.04 KiB            [emitted]  
      fonts/KaTeX_Size2-Regular.woff2  5.09 KiB            [emitted]  
        fonts/KaTeX_Size3-Regular.ttf  7.41 KiB            [emitted]  
       fonts/KaTeX_Size3-Regular.woff  4.32 KiB            [emitted]  
      fonts/KaTeX_Size3-Regular.woff2  3.54 KiB            [emitted]  
        fonts/KaTeX_Size4-Regular.ttf  10.1 KiB            [emitted]  
       fonts/KaTeX_Size4-Regular.woff  5.84 KiB            [emitted]  
      fonts/KaTeX_Size4-Regular.woff2  4.81 KiB            [emitted]  
   fonts/KaTeX_Typewriter-Regular.ttf  26.9 KiB            [emitted]  
  fonts/KaTeX_Typewriter-Regular.woff  15.7 KiB            [emitted]  
 fonts/KaTeX_Typewriter-Regular.woff2  13.3 KiB            [emitted]  
                   js/markbind.min.js   1.3 MiB  markbind  [emitted]  markbind
Entrypoint markbind = js/markbind.min.js
[0] multi webpack-hot-middleware/client ../markbind/packages/core-web/src/index.js 40 bytes {markbind} [built]
[../../node_modules/@babel/runtime/helpers/arrayWithHoles.js] ../markbind/node_modules/@babel/runtime/helpers/arrayWithHoles.js 184 bytes {markbind} [built]
[../../node_modules/@babel/runtime/helpers/defineProperty.js] ../markbind/node_modules/@babel/runtime/helpers/defineProperty.js 367 bytes {markbind} [built]
[../../node_modules/@babel/runtime/helpers/iterableToArrayLimit.js] ../markbind/node_modules/@babel/runtime/helpers/iterableToArrayLimit.js 711 bytes {markbind} [built]
[../../node_modules/@babel/runtime/helpers/nonIterableRest.js] ../markbind/node_modules/@babel/runtime/helpers/nonIterableRest.js 309 bytes {markbind} [built]
[../../node_modules/@babel/runtime/helpers/slicedToArray.js] ../markbind/node_modules/@babel/runtime/helpers/slicedToArray.js 522 bytes {markbind} [built]
[../../node_modules/strip-ansi/index.js] ../markbind/node_modules/strip-ansi/index.js 154 bytes {markbind} [built]
[../../node_modules/webpack-hot-middleware/client-overlay.js] ../markbind/node_modules/webpack-hot-middleware/client-overlay.js 2.14 KiB {markbind} [built]
[../../node_modules/webpack-hot-middleware/client.js] ../markbind/node_modules/webpack-hot-middleware/client.js 7.69 KiB {markbind} [built]
[../../node_modules/webpack-hot-middleware/process-update.js] ../markbind/node_modules/webpack-hot-middleware/process-update.js 4.36 KiB {markbind} [built]
[../../node_modules/webpack/buildin/module.js] ../markbind/node_modules/webpack/buildin/module.js 497 bytes {markbind} [built]
[./src/VueCommonAppFactory.js] ../markbind/packages/core-web/src/VueCommonAppFactory.js 1.09 KiB {markbind} [built]
[./src/index.js] ../markbind/packages/core-web/src/index.js 8.17 KiB {markbind} [built]
[./src/scrollTopButton.js] ../markbind/packages/core-web/src/scrollTopButton.js 1.49 KiB {markbind} [built]
[./src/styles/index.css] ../markbind/packages/core-web/src/styles/index.css 1.09 KiB {markbind} [built]
    + 346 hidden modules
ℹ ｢wdm｣: Compiled successfully.
info: Site data built
info: Website generation complete! Total build time: 0.991s
info: Serving "/Users/peter/Documents/playground/mbtest/_site" at http://127.0.0.1:8080
info: Press CTRL+C to stop ...
```

### Actual behavior

Serving a MarkBind project does not work:

```
peter@Peters-MacBook-Pro markbind % node --version
v18.8.0
peter@Peters-MacBook-Pro mbtest % markbind serve -d
  __  __                  _      ____    _               _ 
 |  \/  |   __ _   _ __  | | __ | __ )  (_)  _ __     __| |
 | |\/| |  / _` | | '__| | |/ / |  _ \  | | | '_ \   / _` |
 | |  | | | (_| | | |    |   <  | |_) | | | | | | | | (_| |
 |_|  |_|  \__,_| |_|    |_|\_\ |____/  |_| |_| |_|  \__,_|
                                                           
 v4.0.2
error: uncaughtException: error:0308010C:digital envelope routines::unsupported date=Thu Nov 17 2022 19:41:32 GMT+0800 (Singapore Standard Time), pid=55424, uid=501, gid=20, cwd=/Users/peter/Documents/playground/mbtest, execPath=/Users/peter/.nvm/versions/node/v18.8.0/bin/node, version=v18.8.0, argv=[/Users/peter/.nvm/versions/node/v18.8.0/bin/node, /Users/peter/.nvm/versions/node/v18.8.0/bin/markbind, serve, -d], rss=160710656, heapTotal=107659264, heapUsed=63658160, external=1108924, arrayBuffers=188336, loadavg=[2.98974609375, 4.03759765625, 5.978515625], uptime=760911
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/peter/Documents/playground/markbind/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/peter/Documents/playground/markbind/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/peter/Documents/playground/markbind/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/peter/Documents/playground/markbind/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/peter/Documents/playground/markbind/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/peter/Documents/playground/markbind/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/peter/Documents/playground/markbind/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/peter/Documents/playground/markbind/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/peter/Documents/playground/markbind/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/Users/peter/Documents/playground/markbind/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/peter/Documents/playground/markbind/node_modules/babel-loader/lib/index.js:59:71
```

**Comment by tlylt** [comment]
Based on this post: https://stackoverflow.com/q/69692842/13725861 it seems to be a problem for node.js v17 onwards, due to webpack (or some other) dependency issues.

@petermonky does the error occur if you run `markbind serve` instead of `markbind serve -d`?

**Comment by petermonky** [comment]
hi @tlylt, the error does not occur with `markbind serve`, it seems like a dev environment issue.

**Comment by tlylt** [comment]
> hi @tlylt, the error does not occur with `markbind serve`, it seems like a dev environment issue.

I see, thanks!

I think it might be webpack V4 that's causing the issue, similar to what others experienced here: https://github.com/webpack/webpack/issues/14532
the workaround suggested in the threads might work if there's an urgent need to use Node v18.8.0 for development.
> export NODE_OPTIONS=--openssl-legacy-provider

Thanks for raising the issue, will need to experiment a little locally to see if upgrading webpack to V5 resolves the issue and whether it is feasible to do a version upgrade without breaking existing setup.
