### ISSUE TITLE
Deleting non-existent logs causes an error

### ISSUE THREAD

**Issue by yamgent** [MarkBind/markbind#213]
**MarkBind Version:** 1.7.2

**Description of Issue:**
Sometimes, when running markbind, the errors in the log below will appear.

This is because the program periodically clears the log files inside `_markbind/logs/`. However, these logs are still documented in `_markbind/logs/audit.json`, so the program will try to delete the log files again, but they no longer exist.

**Temporary Workaround:**
The current workaround is to manually delete `_markbind/logs/audit.json`.

**Log:**

```
warning: Error: EPERM: operation not permitted, stat 'C:\Users\Tan Wang Leng\Documents\GitHub\yamgent\markbind\test\test_site\_markbind\logs\markbind-2018-05-16.log'
error: EPERM: operation not permitted, stat 'C:\Users\Tan Wang Leng\Documents\GitHub\yamgent\markbind\test\test_site\_markbind\logs\markbind-2018-05-16.log'
fs.js:904
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\Tan Wang Leng\Documents\GitHub\yamgent\markbind\test\test_site\_site'
    at Object.fs.readdirSync (fs.js:904:18)
    at _walkSync (C:\Users\Tan Wang Leng\Documents\GitHub\yamgent\markbind\node_modules\walk-sync\index.js:74:18)
    at walkSync (C:\Users\Tan Wang Leng\Documents\GitHub\yamgent\markbind\node_modules\walk-sync\index.js:44:10)
    at Object.<anonymous> (C:\Users\Tan Wang Leng\Documents\GitHub\yamgent\markbind\test\test_site\testUtil\test.js:14:21)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
Test Failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! markbind-cli@1.7.2 testwin: `jest && cd test/test_site && test.bat`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the markbind-cli@1.7.2 testwin script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Tan Wang Leng\AppData\Roaming\npm-cache\_logs\2018-05-16T03_23_53_389Z-debug.log
```

**Comment by damithc** [comment]
Happens to me frequently. Had to delete audit.json each time.

**Comment by Chng-Zhi-Xuan** [comment]
Found a similar issue other users of `winston-daily-rotate-file` are facing [here](https://github.com/winstonjs/winston-daily-rotate-file/issues/125).

There may be a temporary work around to be setting `.exitOnError` to false on `EPERM` errors. However, I'm not sure if our code will throw the same error. 

So the safest option would still be deleting `audit.json` manually?

**Comment by yamgent** [comment]
Or maybe you can try helping them fix their bug 😉.
