### ISSUE TITLE
Unable to run markbind serve from another directory

### ISSUE THREAD

**Issue by marvinchin** [MarkBind/markbind#842]
**Tell us about your environment**

* **MarkBind Version:** v2.2.0

**What did you do? Please include the actual source code causing the issue.**

From `markbind` directory run `markbind serve docs`

**What did you expect to happen?**

Site should build correctly.

**What actually happened? Please include the actual, raw output.**

Got errors:
```
error: uncaughtException: Template render error: (/Users/marvinchin/Documents/Workspace/markbind/docs/userGuide/usingHtmlJavaScriptCss.md)
  Error: template not found: njk/common.njk date=Sun Apr 21 2019 11:26:25 GMT+0800 (+08), pid=6066, uid=501, gid=20, cwd=/Users/marvinchin/Documents/Workspace/markbind, execPath=/Users/marvinchin/.nvm/versions/node/v8.15.1/bin/node, version=v8.15.1, argv=[/Users/marvinchin/.nvm/versions/node/v8.15.1/bin/node, /usr/local/bin/markbind, serve, docs], rss=109539328, heapTotal=78528512, heapUsed=45915760, external=333846, loadavg=[1.16650390625, 1.2783203125, 1.58837890625], uptime=1698463
Template render error: (/Users/marvinchin/Documents/Workspace/markbind/docs/userGuide/usingHtmlJavaScriptCss.md)
  Error: template not found: njk/common.njk
    at Object._prettifyError (/usr/local/lib/node_modules/markbind-cli/node_modules/nunjucks/src/lib.js:36:11)
    at /usr/local/lib/node_modules/markbind-cli/node_modules/nunjucks/src/environment.js:567:19
    at eval (eval at _compile (/usr/local/lib/node_modules/markbind-cli/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:22:11)
    at createTemplate (/usr/local/lib/node_modules/markbind-cli/node_modules/nunjucks/src/environment.js:295:11)
    at next (/usr/local/lib/node_modules/markbind-cli/node_modules/nunjucks/src/lib.js:282:7)
    at handle (/usr/local/lib/node_modules/markbind-cli/node_modules/nunjucks/src/environment.js:329:11)
    at /usr/local/lib/node_modules/markbind-cli/node_modules/nunjucks/src/environment.js:339:9
    at next (/usr/local/lib/node_modules/markbind-cli/node_modules/nunjucks/src/lib.js:280:7)
    at Object.asyncIter (/usr/local/lib/node_modules/markbind-cli/node_modules/nunjucks/src/lib.js:286:3)
    at Environment.getTemplate (/usr/local/lib/node_modules/markbind-cli/node_modules/nunjucks/src/environment.js:321:9)
    at Template.root [as rootRenderFunc] (eval at _compile (/usr/local/lib/node_modules/markbind-cli/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:21:5)
    at Template.render (/usr/local/lib/node_modules/markbind-cli/node_modules/nunjucks/src/environment.js:556:10)
    at Environment.renderString (/usr/local/lib/node_modules/markbind-cli/node_modules/nunjucks/src/environment.js:380:17)
    at Object.renderString (/usr/local/lib/node_modules/markbind-cli/node_modules/nunjucks/index.js:99:14)
    at fs.readFile (/usr/local/lib/node_modules/markbind-cli/src/lib/markbind/src/parser.js:530:36)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

This is caused by references not using relative paths (e.g. njk and includes). I'm not sure if this is expected behaviour (i.e. links should be relative or absolute), or if we should reference all paths from the root folder of the site.

**Comment by marvinchin** [comment]
A quick test shows that changing the working directory to the site root folder (`    process.chdir(rootFolder);`) fixes the issues.

However, I'm looking at the conversation in #202 which seems to solve this programatically. I was wondering if there is any missing context that prevents the issue from being solved by changing the working directory?

**Comment by acjh** [comment]
> This is caused by references not using relative paths (e.g. njk and includes).

Can you elaborate?

> I'm not sure ... if we should reference all paths from the root folder of the site.

Nope. That's why we did #677. If it works with regular Markdown, then MarkBind should support it.

> I was wondering if there is any missing context that prevents the issue from being solved by changing the working directory?

I don't remember this being discussed, but it seems hacky to mimic user action to provide a feature.

**Comment by acjh** [comment]
Related:
- Issue #678 
- PR #684

**Comment by marvinchin** [comment]
> This is caused by references not using relative paths (e.g. njk and includes).

For instance, in `usingHtmlJavaScriptCss.md`, if I change `{% from "njk/common.njk" import previous_next %}` to `{% from "../njk/common.njk" import previous_next %}` the error mentioned above seems to be fixed.

There are new errors such as the one below:
```
[-] 0 / 1 pages builterror:  message=Template render error: (/Users/marvinchin/Documents/Workspace/markbind/docs/userGuide/usingComponents.md)
  Error: template not found: userGuide/fullSyntaxReference.md
Error while preprocessing '/Users/marvinchin/Documents/Workspace/markbind/docs/userGuide/usingHtmlJavaScriptCss.md', stack=Template render error: (/Users/marvinchin/Documents/Workspace/markbind/docs/userGuide/usingComponents.md)
  Error: template not found: userGuide/fullSyntaxReference.md
    at Object._prettifyError (/Users/marvinchin/Documents/Workspace/markbind/node_modules/nunjucks/src/lib.js:36:11)
    at /Users/marvinchin/Documents/Workspace/markbind/node_modules/nunjucks/src/environment.js:567:19
    at eval (eval at _compile (/Users/marvinchin/Documents/Workspace/markbind/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:16:11)
    at createTemplate (/Users/marvinchin/Documents/Workspace/markbind/node_modules/nunjucks/src/environment.js:295:11)
    at next (/Users/marvinchin/Documents/Workspace/markbind/node_modules/nunjucks/src/lib.js:282:7)
    at handle (/Users/marvinchin/Documents/Workspace/markbind/node_modules/nunjucks/src/environment.js:329:11)
    at /Users/marvinchin/Documents/Workspace/markbind/node_modules/nunjucks/src/environment.js:339:9
    at next (/Users/marvinchin/Documents/Workspace/markbind/node_modules/nunjucks/src/lib.js:280:7)
    at Object.asyncIter (/Users/marvinchin/Documents/Workspace/markbind/node_modules/nunjucks/src/lib.js:286:3)
    at Environment.getTemplate (/Users/marvinchin/Documents/Workspace/markbind/node_modules/nunjucks/src/environment.js:321:9)
    at Template.root [as rootRenderFunc] (eval at _compile (/Users/marvinchin/Documents/Workspace/markbind/node_modules/nunjucks/src/environment.js:637:18), <anonymous>:15:5)
    at Template.render (/Users/marvinchin/Documents/Workspace/markbind/node_modules/nunjucks/src/environment.js:556:10)
    at Environment.renderString (/Users/marvinchin/Documents/Workspace/markbind/node_modules/nunjucks/src/environment.js:380:17)
    at Object.renderString (/Users/marvinchin/Documents/Workspace/markbind/node_modules/nunjucks/index.js:99:14)
    at Parser._preprocess (/Users/marvinchin/Documents/Workspace/markbind/src/lib/markbind/src/parser.js:278:28)
```
which seems to stem from the include generated by the nunjucks code not being found, but the nunjucks code itself seems to be "included" correctly. 

I believe that this is because the paths are all treated as relative to the current working directory of the process (e.g. `njk/common.njk` searches for the folder `njk` in the process's cwd).

Thanks for pointing out #678, I missed it somehow when scanning the issues. It seems fairly similar. Should we mark this issue as a duplicate and close it?

**Comment by acjh** [comment]
Thanks for the clarification.

> Should we mark this issue as a duplicate and close it?

I'm not sure here. @nicholaschuayunzhi @yamgent?

**Comment by marvinchin** [comment]
After examining this issue further, it seems like the error is caused solely by nunjucks file paths, and not includes (I had misunderstood the error message). I think it can safely be marked as a duplicate of #678.

Apologies for any inconvenience!

**Comment by marvinchin** [comment]
Duplicate of #678.
